const elements = [
  { atno: 1, name: 'hydrogen', symbol: 'H' }, 
  { atno: 2, name: 'helium', symbol: 'He' }, 
  { anto: 3, name: 'lithium', symbol: 'Li'},
  { atno: 4, name: 'beryllium', symbol: 'Be' }, 
  { atno: 5, name: 'boron', symbol: 'B'},
  { atno: 6, name: 'carbon', symbol: 'C'},
  { atno: 7, name: 'nitrogen', symbol: 'N'},
  { atno: 8, name: 'oxygen', symbol: 'O'},
  { atno: 9, name: 'fluorine', symbol: 'F'},
  { atno: 10, name: 'neon', symbol: 'Ne'},
  { atno: 11, name: 'sodium', symbol: 'Na'},
  { atno: 12, name: 'magnesium', symbol: 'Mg'},
  { atno: 13, name: 'aluminum', symbol: 'Al'},
  { atno: 14, name: 'silicon', symbol: 'Si'},
  { atno: 15, name: 'phosphorus', symbol: 'P'},
  { atno: 16, name: 'sulfur', symbol: 'S'},
  { atno: 17, name: 'chlorine', symbol: 'Cl'},
  { atno: 18, name: 'argon', symbol: 'Ar'},
  { atno: 19, name: 'potassium', symbol: 'K'},
  { atno: 20, name: 'calcium', symbol: 'Ca'},
  { atno: 21, name: 'scandium', symbol: 'Sc'},
  { atno: 22, name: 'titanium', symbol: 'Ti'},
  { atno: 23, name: 'vanadium', symbol: 'V'},
  { atno: 24, name: 'chromium', symbol: 'Cr'},
  { atno: 25, name: 'manganese', symbol: 'Mn'},
  { atno: 26, name: 'iron', symbol: 'Fe'},
  { atno: 27, name: 'cobalt', symbol: 'Co'},
  { atno: 28, name: 'nickel', symbol: 'Ni'},
  { atno: 29, name: 'copper', symbol: 'Cu'},
  { atno: 30, name: 'zinc', symbol: 'Zn'},
  { atno: 31, name: 'gallium', symbol: 'Ga'},
  { atno: 32, name: 'germanium', symbol: 'Ge'},
  { atno: 33, name: 'arsenic', symbol: 'As'},
  { atno: 34, name: 'selenium', symbol: 'Se'},
  { atno: 35, name: 'bromine', symbol: 'Br'},
  { atno: 36, name: 'krypton', symbol: 'Kr'},
  { atno: 37, name: 'rubidium', symbol: 'Rb'},
  { atno: 38, name: 'strontium', symbol: 'Sr'},
  { atno: 39, name: 'yttrium', symbol: 'Y'},
  { atno: 40, name: 'zirconium', symbol: 'Zr'}
]

export default elements;